apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      service: {{.Release.Name}}
  template:
    metadata:
      labels:
        service: {{.Release.Name}}
    spec:
      containers:
        - name: main
          image: {{.Values.image}}
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
