apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      service: {{.Release.Name}}
  template:
    metadata:
      labels:
        service: {{.Release.Name}}
    spec:
      containers:
        - name: main
          image: {{.Values.image}}
          imagePullPolicy: IfNotPresent
          env:
            - name: REGISTRY_URLS
              value: http://registry1:8080/eureka,http://registry2:8080/eureka
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
