apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{.Release.Name}}
  namespace: default
spec:
  gateways:
    - istio-external-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /api/{{.Release.Namespace}}/{{.Release.Name}}
      rewrite:
        uri: /
      route:
        - destination:
            host: {{.Release.Name}}.{{.Release.Namespace}}.svc.cluster.local
            port:
              number: 8080
