# Services are accessible via http://internal.k8s/{namespace}/{service}/...

internal_access:
  namespaces:
    - green
    - blue
    - proxy
  services:
    - main
    - hello
    - time
    - proxy
