apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: proxy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: CUSTOM
  provider:
    name: proxy
  rules:
    - to:
        - operation:
            hosts: [ "external.k8s" ]
